##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-polkit
    - autoconf-archive
    - gcc
    - git
    - gtk3
    - intltool
    - libappindicator-gtk3
    - make
    - mate-common
    - polkit
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-polkit
    - git
    - libappindicator3-dev
    - libgtk-3-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - make
    - mate-common

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-polkit.git
    - gcc
    - git
    - gtk3-devel
    - libappindicator-gtk3-devel
    - make
    - mate-common
    - polkit-devel
    - redhat-rpm-config

  ubuntu:
    - git
    - libappindicator3-dev
    - libgtk-3-dev
    - libpolkit-agent-1-dev
    - libpolkit-gobject-1-dev
    - make
    - mate-common

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-polkit-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release

